# configuration file for Lightstep GitHub Action

organization: LightStep
project: Robin-Hipster-Shop

integrations:
  rollbar:
    environment: production
    account: lightstep
    project: Lightstep-Hipster-Shop
  pagerduty:
    service: PA0B3RR
