# configuration file for Lightstep GitHub Action

organization: LightStep
project: demo

services:
  android:
    integrations:
      pagerduty:
        service: PXTW6XZ
  iOS:
    path: ./src/cartservice
    integrations:
      pagerduty:
        service: PXTW6XZ
  profile:
  krackend-api-gateway:
  inventory:
  web:
    violations:
      - name: No requests to currency service
        type: connection
        value: krackend-api-gateway
      - name: No 500s Allowed
        type: span.attributes
        key: http.status_code
        op: equals
        value: 500
      - name: No us-east-2
        type: span.attributes
        key: cloud.region
        op: equals
        value: us-east-2
    integrations:
      pagerduty:
        service: PXTW6XZ

conditions:
  - 9k8QvPSw
  - XvKgrQyj
  - tC5CTBWt

integrations:
  rollbar:
    environment: production
    account: lightstep
    project: Lightstep-Hipster-Shop

