name: Lightstep PR Workflow
on: 
  pull_request:
#   pull_request_review:
#    types: [submitted]

env:
  LIGHTSTEP_API_HOST: api-staging.lightstep.com
  LIGHTSTEP_API_TOKEN: ${{ secrets.LIGHTSTEP_API_TOKEN }}
  ROLLBAR_API_TOKEN: ${{ secrets.ROLLBAR_API_TOKEN }}

jobs:    
  deploy_check_job:
    runs-on: ubuntu-latest
    name: Lightstep Pre-Deploy Check

    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lightstep Pre-Deploy Check
        uses: ./actions/lightstep-predeploy
        id: lightstep-predeploy
      - name: Add Comment
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.lightstep-predeploy.outputs.lightstep_predeploy_md }}
          check_for_duplicate_msg: true