name: Lightstep PR Workflow
on: 
  pull_request:
#   pull_request_review:
#    types: [submitted]

env:
  LIGHTSTEP_API_HOST: api-staging.lightstep.com

jobs:    
  deploy_check_job:
    runs-on: ubuntu-latest
    name: Lightstep Pre-Deploy Check

    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      # checkout the private repo containing lightstep action
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: lightstep/lightstep-action-predeploy
          ref: master
          token: ${{ secrets.SMITHCLAY_PAT }}
          path: .github/actions/lightstep-action-predeploy
      - name: Lightstep Pre-Deploy Check
        id: lightstep-predeploy
        uses: ./.github/actions/lightstep-action-predeploy
        with:
          lightstep_api_key: ${{ secrets.LIGHTSTEP_API_TOKEN }}
          pagerduty_api_token: ${{ secrets.PAGERDUTY_API_TOKEN }}
          rollbar_api_token: ${{ secrets.ROLLBAR_API_TOKEN }}
      - name: Echo Status
        run: echo ${{ steps.lightstep-predeploy.outputs.lightstep_predeploy_status }}
      - name: Take Lightstep Snapshot
        id: lightstep-snapshot
        if: ${{ steps.lightstep-predeploy.outputs.lightstep_predeploy_status != 'ok' }}
        with:
          lightstep_api_key: ${{ secrets.LIGHTSTEP_API_TOKEN }}
          lightstep_organization: ${{ steps.lightstep-predeploy.outputs.lightstep_organization }}
          lightstep_project: ${{ steps.lightstep-predeploy.outputs.lightstep_project }}
          lightstep_service: 'frontend'
        uses: ./actions/lightstep-snapshot
      - name: Add Comment
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.lightstep-predeploy.outputs.lightstep_predeploy_md }}
          check_for_duplicate_msg: true