name: Attach Snapshot to Issue

on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  add_snapshot_to_issue:
    runs-on: ubuntu-latest
    name: Take Snapshot
    if: contains(github.event.issue.labels.*.name, 'bug')

    steps:
      - run: |
          export
          echo $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH

      # Needed if reading configuration from `.lightstep.yml`
      - name: 🛎️ Checkout
        if: success()
        uses: actions/checkout@v2

      - name: 📸 Take Lightstep Snapshot
        id: lightstep-snapshot
        uses: lightstep/lightstep-action-snapshot@v2
        with:
          lightstep_api_key: ${{ secrets.LIGHTSTEP_API_TOKEN }}
          lightstep_organization: LightStep
          lightstep_project: demo
          pagerduty_api_token: ${{ secrets.PAGERDUTY_API_TOKEN }}
          rollbar_api_token: ${{ secrets.ROLLBAR_API_TOKEN }}
          # query that always returns data in the test env
          lightstep_snapshot_query: '"service.version" NOT IN ("baz")'
#         Recommended query based on SHA:
#         lightstep_snapshot_query: '"github.sha" IN ("${{ github.sha }}")'
     
      # Wait ~4 minutes for the snapshot to complete
      - name: Wait for Snapshot to Complete
        run: sleep 240

      - name: Get Snapshot Summary
        id: lightstep-snapshot-summary
        uses: lightstep/lightstep-action-snapshot@v2
        if: ${{ steps.lightstep-predeploy.outputs.lightstep_predeploy_status != 'ok' }}
        # Pass LS_ACCESS_TOKEN if you want to see traces of the action (cool!)
        env:
          LS_ACCESS_TOKEN: ${{ secrets.LS_ACCESS_TOKEN }}
        with:
          lightstep_api_key: ${{ secrets.LIGHTSTEP_API_TOKEN }}
          lightstep_snapshot_id: ${{ steps.lightstep-snapshot.outputs.lightstep_snapshot_id }}

      - name: Add Snapshot Summary to Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.lightstep-snapshot-summary.outputs.lightstep_snapshot_diff_md }}
