name: Attach Lightstep Snapshot to Issue

on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  add_snapshot_to_issue:
    runs-on: ubuntu-latest
    name: Take Snapshot
    # Run this if an issue has the label 'bug'
    if: contains(github.event.issue.labels.*.name, 'bug')

    steps:
      - run: |
          export
          echo $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH

      # Check out the repo to read configuration 
      # from the `.lightstep.yml` file in the repo root directory.
      - name: 🛎️ Checkout
        if: success()
        uses: actions/checkout@v2

      - name: 📸 Take Lightstep Snapshot
        id: take-lightstep-snapshot
        uses: lightstep/lightstep-action-snapshot@v2
        with:
          lightstep_api_key: ${{ secrets.LIGHTSTEP_API_TOKEN }}
          #
          # Pass in partner API token integrations
          pagerduty_api_token: ${{ secrets.PAGERDUTY_API_TOKEN }}
          rollbar_api_token: ${{ secrets.ROLLBAR_API_TOKEN }}
          #
          # Infer a recent snapshot to compare with using the API
          # '*' uses most recent available (per project or repo tag if exists)
          lightstep_snapshot_compare_id: '*'
          # Query for the snapshot
          # Recommended to use a query based on SHA:
          # lightstep_snapshot_query: '"github.sha" IN ("${{ github.sha }}")'
          lightstep_snapshot_query: '"service.version" NOT IN ("baz")'

      - name: Wait for Snapshot to Complete
        run: sleep 240

      - name: Cache Snapshots
        id: cache-snapshots
        uses: actions/cache@v2
        with:
          path: /tmp/lightstep
          key: ${{ steps.take-lightstep-project.outputs.lightstep_project }}-snapshots

      - name: Get Snapshot Summary
        id: lightstep-snapshot-summary
        uses: lightstep/lightstep-action-snapshot@v2
        with:
          lightstep_api_key: ${{ secrets.LIGHTSTEP_API_TOKEN }}
          lightstep_snapshot_id: ${{ steps.lightstep-snapshot.outputs.lightstep_snapshot_id }}

      - name: Add Snapshot Summary to Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.lightstep-snapshot-summary.outputs.lightstep_snapshot_md }}
