name: Lightstep Terraform Resources

on: [workflow_dispatch]

# with assistance from: https://github.com/lermsai/infra-live/blob/2179c25aba01c7d6a7498bc4939dd614185407da/.github/workflows/main.yml
env:
  LIGHTSTEP_API_HOST: api-staging.lightstep.com
  TF_VAR_lightstep_access_token: ${{ secrets.LIGHTSTEP_API_TOKEN }}
  LIGHTSTEP_API_TOKEN: ${{ secrets.LIGHTSTEP_API_TOKEN }}

jobs:
  build-custom-provider:
    name: Build Private Terraform provider
    runs-on: ubuntu-latest
    steps:
    - name: Checkout private terraform provider
      uses: actions/checkout@v2
      with:
        repository: lightstep/terraform-provider-lightstep 
        token: ${{ secrets.SMITHCLAY_PAT }}

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Build provider
      run: |
        go build -o terraform.d/plugins/linux_amd64/terraform-provider-lightstep
        ls -al
        pwd

    - name: Upload provider artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform.d
        path: terraform.d

  terraform:
    needs: [build-custom-provider]
    name: 'Run Terraform'
    runs-on: ubuntu-latest
    env:
      TF_VAR_lightstep_org: '-13a29ef7'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Download custom provider binaries'
      uses: actions/download-artifact@v1
      with:
        name: terraform.d

    - name: 'Make binary executable'
      run: chmod +x ./terraform.d/plugins/linux_amd64/terraform-provider-lightstep

    - name: 'Move custom terraform providers to plugin directory'
      run: |
        mv ./terraform.d ${HOME}/.terraform.d

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform providers
        terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      continue-on-error: true

#    - name: Terraform Apply
#      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
#      run: terraform apply -auto-approve
